book_repo: pivotal-cf/docs-book-mysql-k8s
layout_repo: pivotal-cf/docs-layout-repo
layout_repo_ref: 'master'

feedback_enabled: true

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

public_host: docs.pivotal.io

elastic_search: true

sections:
# cross-product resources
- repository:
    name: pivotal-cf/docs-partials
    ref: master
  directory: mysql-k8s/partials
  no_docs: true

- repository:
    name: pivotal-cf/docs-mysql-k8s
    ref: '0.2'
  directory: tanzu-mysql-kubernetes/0-2
  subnav_template: mysql_k8s_subnav_0_2.erb
  product_info:
    use_local_header: true
    latest_stable_version: 0.2
    changelog_href: http://docs.pivotal.io/tanzu-mysql-kubernetes/0-2/release-notes.html
    local_header_img: /images/cloud_rings.png
    local_header_title: VMware Tanzu™ SQL with MySQL for Kubernetes
    search_placeholder: Tanzu MySQL for Kubernetes (Beta) v0.2
    url_prefix: tanzu-mysql-kubernetes/0-2
    local_product_version: '0.2'
    local_header_links: []
    local_header_version_list:
      - url_prefix: http://docs.pivotal.io/tanzu-mysql-kubernetes/0-1
        display_name: 0.1
